# Generated by Django 4.1.4 on 2022-12-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad", name="price", field=models.PositiveIntegerField(default=0),
        ),
    ]
